#!/bin/bash

# sudo apt-get install wmctrl xdotool

#SWITCH_DIR="/tmp/showwin/$1"
SWITCH_DIR="/dev/shm/$USER/showwin/$1"

LAST_DIR="$SWITCH_DIR/../showwin_last"
mkdir -p "$SWITCH_DIR"
rm -r "$LAST_DIR"
ln -s "$SWITCH_DIR" "$LAST_DIR"

PINNED_ID=`ls "$SWITCH_DIR"`

# echo "Pinned $PINNED_ID"

MATCHED_WIN=`wmctrl -l -x | grep -i "$1\|^$PINNED_ID "`
if [[ -z $MATCHED_WIN && -z $2 ]]; then
  echo "Assigning new window"
  MATCHED_WIN=`wmctrl -l -x`
fi

CURRENT_ID=`xdotool getwindowfocus`
CURRENT_ID=`printf "0x%08x" $CURRENT_ID`
MATCHED_CURRENT_ID=`echo "$MATCHED_WIN" | grep "^$CURRENT_ID " | head -1 | cut -d" " -f1`
MATCHED_PINNED_ID=`echo "$MATCHED_WIN" | grep "^$PINNED_ID " | head -1 | cut -d" " -f1`

if [[ -n $MATCHED_PINNED_ID ]]; then
  MATCHED_ID=$MATCHED_PINNED_ID
elif [[ -n $MATCHED_CURRENT_ID ]]; then
  MATCHED_ID=$MATCHED_CURRENT_ID
else
  MATCHED_ID=`echo "$MATCHED_WIN" | head -1 | cut -d" " -f1`
fi

# echo "Matched current $MATCHED_CURRENT_ID"
# echo "Matched pinned $MATCHED_PINNED_ID"
# echo "Matched $MATCHED_ID"

  
if [[ -n "$MATCHED_CURRENT_ID" ]] && [[ "$MATCHED_PINNED_ID" -eq "$MATCHED_CURRENT_ID" ]]; then
  echo "Minimize"
  xdotool getactivewindow windowminimize
elif [[ -n $MATCHED_ID ]]; then
  echo "Switching to window $MATCHED_ID"
  wmctrl -a $MATCHED_ID -i
elif [[ -n $2 ]]; then
  echo "Opening new window $2"
  $2&
  
  # wait up to 5 seconds while window is opening
  end=$((SECONDS+5))
  while [[ -z `wmctrl -l -x | grep -i "$1"` && $SECONDS -lt $end ]]; do
    sleep 0.2
  done
  MATCHED_ID=`wmctrl -l -x | grep -i "$1" | head -1 | cut -d" " -f1`
  wmctrl -a $MATCHED_ID -i
fi


if [[ -n $MATCHED_ID ]]; then
  rm -r "$SWITCH_DIR"/* > /dev/null
  mkdir -p "$SWITCH_DIR/$MATCHED_ID"
fi
