#!/bin/bash

# To export hotkeys use this command:
# dconf dump /org/gnome/settings-daemon/plugins/media-keys/ > gnome-hotkeys

dconf load /org/gnome/settings-daemon/plugins/media-keys/ < gnome-hotkeys
